//question 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//helper function
var isEven = num => num % 2 == 0;




//function to create fibonacci sequence 
var sequence = function(){
    fibSeq = [0,1];
    i=1;
    
    while(fibSeq[i]<4000000){
    nextNum = fibSeq[i] + fibSeq[i-1];
    fibSeq.push(nextNum);
    i++;
    
}


console.log("fibonacci sequence length is "+fibSeq.length);
var sol = 0;

for (j=0;j<fibSeq.length; j++){
    
    if(isEven(fibSeq[j])){
        sol += fibSeq[j];
    }
    
}
console.log("solution is " + sol);
}

sequence();